version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: /ann-project/dockerhub/username
    DOCKER_TOKEN: /ann-project/dockerhub/token
    DOCKER_REGISTRY: /ann-project/dockerhub/registry

phases:

  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt

      - echo "Logging in to Docker Hub..."
      - echo "$DOCKER_TOKEN" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t "$DOCKER_USERNAME/ann-project:latest" .

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push "$DOCKER_USERNAME/ann-project:latest"
      - echo "Docker Build and Push Successful"